image:
  file: .gitpod.Dockerfile

tasks:
  - name: build and prep goof
    init: |
      export NVM_DIR="/workspace/.nvm"
      mkdir -p $NVM_DIR
      curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | PROFILE=/dev/null bash
      cp /home/gitpod/.nvm/nvm-lazy.sh /workspace/.nvm/nvm-lazy.sh
      sed -i 's/\$HOME/\/workspace/g' /workspace/.nvm/nvm-lazy.sh
      echo ". /workspace/.nvm/nvm-lazy.sh"  >> /home/gitpod/.bashrc.d/50-node
      source $NVM_DIR/nvm.sh
      nvm install 14.1.0
      nvm use 14.1.0
      npm install
    command: |
      docker image pull mongo:5.0.13
      docker image pull mysql:5
      docker compose up -d goof-mysql goof-mongo
      snyk auth
      npm start
  - name: shell
    command: /bin/bash
    openMode: tab-after
ports:
  - name: Goof Page
    port: 3001
    onOpen: open-preview
vscode:
  extensions:
    - https://github.com/snyk/vscode-extension/releases/download/v1.6.1/snyk-vulnerability-scanner-1.6.1.vsix